user_auth/accounts/urls.py
# myapp's urls.py
from django.urls import path
from . import views
from .views import indexPage

app_name = "accounts"

urlpatterns = [
    # path("", views.index, name="index"),
    path("",views.indexPage,name='home'),
    path("user/", views.UserCreated, name="user"),
    path("cert-page",views.Certicate.as_view(),name='cert-page')
]

# urls.py
# from django.urls import re_path as url


# from . import views


# app_name = 'quiz_app'

# urlpatterns = [
#     url("quiz_page", views.QuestionView.as_view(),name='quiz-page'),  
#     ]

user_auth/quiz_app/urls.py
# urls.py
from django.urls import re_path as url


from . import views


app_name = 'quiz_app'

urlpatterns = [
    url("quiz_page", views.QuestionView.as_view(),name='quiz-page'),  
    ]

user_auth/user_auth/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('quiz_app/',include("quiz_app.urls")),
    path('accounts/',include('accounts.urls')),
]

user_auth/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# from django.contrib.auth.base_user import AbstractBaseUser
# Create your models here.

user_role_choices = (
    ("SuperUser","Super User"),
    ("StandardUser","Standar User")
)

class Certificate(models.Model):
    name = models.CharField(max_length=255,null=True,blank=True)

    def __str__(self):
        return str(self.name)

class User(AbstractUser):
    mobile_no = models.CharField(max_length=20,null=True,blank=True)
    cert = models.ManyToManyField(Certificate)

    def __str__(self):
        return str(self.username)

class Employee(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=60)
    email = models.EmailField(blank=True)
    day_started = models.DateField()
    location = models.CharField(max_length=100, blank=True)

    def __str__(self):

        return self.first_name+''+self.last_name


from datetime import date
class TimeTrack(models.Model):
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()

    @property
    def get_time(self):
        print("adasd")
        from datetime import timedelta
    
        a = self.start_date
        b = self.end_date

        if self.end_date is not None:
            time_difference = b - a
            print(time_difference/timedelta(1))
            return time_difference


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True,related_name="user_profile")
    phone = models.CharField(max_length=255,blank=True,null=True)
    is_verified = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.email

user_auth/quiz_app/models.py
from django.db import models
from ordered_model.models import OrderedModel
from django_extensions.db.models import TimeStampedModel

# Create your models here.


class Question(models.Model):
    name = models.CharField(max_length=50,null=True,blank=True,verbose_name="Question Name")
    text = models.TextField()

    def __str__(self):
        return self.name

class Answer_Choice(OrderedModel):
    answer_choice = models.TextField()
    score = models.IntegerField()
    question = models.ForeignKey(Question, default=1, verbose_name="Category", on_delete=models.CASCADE)
    order_with_respect_to = 'question'

    class Meta:
        ordering = ('question', 'order')

user_auth/accounts/forms.py
# accounts/forms.py

from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import User

class MyUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = User
        fields = ('username', 'mobile_number', 'birth_date')

class MyUserChangeForm(UserChangeForm):

    class Meta(UserChangeForm):
        model = User
        fields = ('username', 'mobile_number', 'birth_date')

user_auth/accounts/views.py
from django.shortcuts import render
from django.http import HttpResponse
from tablib import Dataset
from django.utils import timezone
from .admin import EmployeeResource
from .models import *
from django.utils.timezone import localtime
from datetime import datetime
from dateutil import tz
from django.views import View


def indexPage(request):
   users = User.objects.all()
   print(users)
   # request.COOKIES.get('timeZone')
   request.session['timeZone'] = request.COOKIES.get('timeZone')
   # request.COOKIES.get('timeZone')
   
   # print(request.session['timeZone'])
   print(request.COOKIES.get('timeZone'))
   context={
      'user':users

   }
   return render(request,'home.html',context)

def UserCreated(request):
   user_data =  User.objects.all()
   user_time = User.objects.values_list('date_joined',flat=True)
   while True:
      request.session['timeZone'] = request.COOKIES.get('timeZone')
      timezone = request.session['timeZone'] 
      context = {
         'user':user_data,
         'timeZone':timezone
      }
   # print(request.user.timezone)
      return render(request,'user.html',context)


class Certicate(View):
   def get(self,request):

      user_cert = User.objects.filter(username=request.user).order_by('pk')

      a = TimeTrack.objects.all()

      context = {'user_cert':user_cert,'time_track':a}

      # user_cert = User.objects.select_related('cert').all()
      # all_cert = Certificate.objects.all()
      # cert_data = request.GET.get('cert_data')
      # print(cert_data)
      # if cert_data is not None:
      #    val_cer = Certificate.objects.create(name=cert_data)
      #    val_cer.save()
      # print("DONE")
      # context = {
      #    'cert':'CERTIFICATE PAGE',
      #    'user_cert':user_cert,
      #    'all_cert':all_cert
      # }



      return render(request,'accounts/cert.html',context)

user_auth/quiz_app/views.py
from django.shortcuts import render
from django.db.models import Prefetch

# Create your views here.
from quiz_app.models import *
from django.views import View

class QuestionView(View):
    def get(self,request):
        question_category_qs = Question.objects.prefetch_related('answer_choice_set').filter(pk=1)
        print('qqqqqqq',question_category_qs)
        print(Answer_Choice.objects.get(pk=1))
        print(Answer_Choice.objects.all())
        print('orderBY',Answer_Choice.objects.all().order_by('order'))

        print('----->',Question.objects.prefetch_related(Prefetch('answer_choice_set', queryset=Answer_Choice.objects.order_by('order'), to_attr='rgs')).all())

        context = {'a':Question.objects.prefetch_related(Prefetch('answer_choice_set', queryset=Answer_Choice.objects.order_by('order'))).all()}
        
    
        return render(request,"quest.html",context)

user_auth/accounts/templates/accounts/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
</head>
<body>
    <h1>base.html</h1>
</body>
</html>

user_auth/accounts/templates/accounts/cert.html
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
{% if request.user.is_superuser %}

    <!-- <h1>{{cert}} </h1>
    <h1>Your certificate : {{user_cert.first_name}}</h1>

    <select name="cert" id="cert">
    {% for i in user_cert %}
        <option value="{{i.pk}}">{{i.cert.name}}</option>
    {% endfor %}
</select>

    {% endif %} -->
    <h1>start</h1>
    {% for i in user_cert %}
    {% for j in i.cert.all %}
    <h1>{{j}}</h1>

    {% endfor %}
    {% endfor %}

<hr>
    {% for i in user_cert %}
    <h1>{{i.username}}</h1>
    <h1>{{i.cert.all|join:"<br>"}}</h1>
    {% endfor %}


    {% for i in time_track %}
    <h1>{{i.get_time}}</h1>
    {% endfor %}

    <input type="text" name="add-cert" id="add-cert">
    <button type="button" id="save-cert">SAVE</button>
       

<script>
   
    
    $("#save-cert").on('click',function () {
        var cert_data = document.getElementById('add-cert').value;
        console.log(document.getElementById('add-cert').value)
        console.log("CERTDATA",cert_data)  
      $.ajax({
        url: "{% url 'accounts:cert-page' %}",
        method: "GET", // or "get"
        data: {'cert_data':document.getElementById('add-cert').value},
        headers: { "X-CSRFToken": "{{ csrf_token }}" }, // for csrf token
        success: function (data) {
          //  console.log(data)  

          document.getElementById('add-cert').value = '';
            
            console.log("WORKING")
         // console.log(data);
        },
      });
    });
  

  
</script>

user_auth/accounts/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    {% for i in user %}
    <h1>{{i.username}}</h1>
    {% endfor %}


    <a class="btn btn-outline-secondary"  href="{% url 'accounts:user' %}">View User Creation time</a>



</body>
</html>

user_auth/accounts/templates/user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    
</head>
<body>
    
    {% load tz %}

            {% for i in user %}


     <h1 class="date-joined">DATES
        <script></script>
        <p class="value">{{i.date_joined|timezone:timeZone}}</p>
     </h1>
    {% endfor %}

<script>
    const timeZone = Intl.DateTimeFormat().resolvedOptions().timeZone;
    document.cookie = "timeZone="+timeZone;
</script>
</body>
</html>

user_auth/accounts/templates/user_reg.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    

    <script>

    $.ajax({
        
    })
    </script>
</body>
</html>

user_auth/quiz_app/templates/quest.html
{% for i in a %}
    <h1>{{i}}</h1>
    {% for j in i.answer_choice_set.all %}
    <h1>{{j.answer_choice}}</h1>
    {% endfor %}
    {% endfor %}